#!/usr/bin/env bash
# Installs and configures nginx with required content and redirection.

set -e

apt-get -y update
apt-get -y install nginx

echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html

if ! grep -q "location /redirect_me" /etc/nginx/sites-available/default; then
  sed -i "/server_name _;/a\\
\\
    location /redirect_me {\\
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\
    }" /etc/nginx/sites-available/default
fi

service nginx restart
