#!/usr/bin/env bash
# Installs nginx with redirect and a custom 404 page.

set -e

apt-get -y update
apt-get -y install nginx

echo "Holberton School for the win!" > /var/www/html/index.html
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

cat <<'EOF' > /etc/nginx/sites-available/default
http {
    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;

        location /redirect_me {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }

        error_page 404 /404.html;
        location = /404.html {
            internal;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
EOF

service nginx restart || service nginx start
